### ISSUE TITLE
Decimal Point not working

### ISSUE THREAD

**Issue by solarmon** [coopzone-dc/GotekLEDC68#1]
Hi,

Thank you very much for this LEDC68 library! I'm trying to use it for a project of mine.

However, I can't seem to get the decimal point to work. I realise that you have already documented that this function is currently not working, but it also suggests that the last two decimal points should displayed. But I cannot get these to appear at all.

I calling the function with:

Display.displayDP(1);

I've tried 0 and 2 values also, but the decimal point does not appear at all.

I would like to get the second decimal point showing, so is there a way of doing this manually?

Thank you in advance for your help.

**Comment by coopzone-dc** [comment]
Thanks for using the library and your kind words.

Unfortunately the issue with the decimal point, after investigation, is not an issue with the software.

I have several of these displays (some I just sell on ebay, some I use) and having studied the circuit diagram for the display board and a bit of reverse engineering I can conclude:

1, The library correctly send the instructions to activate the DP.
2, Some boards don't have the pin connected form the driver chip to the displays on the board!
3, Some boards use a cheaper version of the displays that do not have the DP LED present at all.
4, Some displays only have one DP LED in place (just after the last digit).

It seems very much pot-luck if you happen to get a version of the board that has one LED DP in the last digit, if you do and it's connected! it works! (It is possible but unless you are very good at soldering and have a suitable soldering iron to overcome no 2 above by jumpering the chip on the board)

I left the code in the library so that anyone interested could see it and if you where lucky enough to have a board that was correctly wired, use it.

Sorry but it's not fixable.

Derek

**Comment by solarmon** [comment]
Hi Derek (F?)

Thank you for the detailed reason as to why the DP is not working.

I'm using this LED screen for floppy drive track display and wanted to use the second DP and digit to show what side the head is on - i.e. ".0" or ".1".

The workaround I have used to use the third digit with either the upper or lower segment to indicate the head side.

Thank you once again for this library, which has greatly helped me in my project!

**Comment by coopzone-dc** [comment]
Closing for now
